#!/usr/bin/env python3
"""
Train on segments including augmented variations (pitch + speed)
Uses PRECOMPUTED mel spectrograms from mels/ and mels/augmented/ directories

Implements custom learning rate decay: start at 1e-3, decay by 10% when loss increases, stop at 1e-7

Usage:
  python3 train_augmented.py <dataset_name> all                # Train all parts with augmentation
  python3 train_augmented.py <dataset_name> <surah_part>       # Train specific part with augmentation

Examples:
  python3 train_augmented.py Quran-A all            # Train all parts
  python3 train_augmented.py Quran-A 001            # Train on Al-Fatiha (001)
  python3 train_augmented.py Quran-A 002-04         # Train on Al-Baqara part 4

Prerequisites:
  - Run generate_mels.py first to generate regular mels
  - Run generate_augmented.py to generate augmented audio
  - Run generate_mels.py again to generate augmented mels
"""
import sys
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

# Force unbuffered output for real-time logging
sys.stdout.reconfigure(line_buffering=True)
sys.stderr.reconfigure(line_buffering=True)

import json
import torch
import torch.nn as nn
import torchaudio
import glob
import os
import random
import time
sys.path.append("..")
from tools.encoder_decoder_transformer import EncoderDecoderTransformer

# ==============================================================
# Device setup
# ==============================================================
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

# ==============================================================
# Audio feature extraction
# ==============================================================
def load_mel_features(mel_path, target_seconds=None):
    """
    Load PRECOMPUTED mel features from .pt file
    These were generated by generate_mels.py (not computed on-the-fly)

    Args:
        mel_path: Path to .pt file containing mel spectrogram
        target_seconds: Optional duration to truncate audio (for curriculum learning)
    """
    if not os.path.exists(mel_path):
        raise FileNotFoundError(f"Precomputed mel features not found: {mel_path}\nPlease run generate_mels.py first")

    mel_features = torch.load(mel_path, map_location='cpu', weights_only=True)

    # Truncate if target_seconds is specified (for curriculum learning)
    if target_seconds is not None:
        # Mel features are at 100 fps (frames per second)
        target_frames = int(target_seconds * 100)
        if mel_features.shape[0] > target_frames:
            mel_features = mel_features[:target_frames, :]

    return mel_features

# ==============================================================
# Tokenization
# ==============================================================
def tokenize_text(text, vocab):
    word_to_idx = {word: idx for idx, word in enumerate(vocab)}
    words = text.split()
    return [word_to_idx.get(word, 0) for word in words]

# ==============================================================
# Text normalization
# ==============================================================
def normalize_text(text):
    """Normalize Arabic text by removing diacritics and extra spacing"""
    normalized = text.replace("َ", "").replace("ً", "").replace("ُ", "").replace("ِ", "")
    normalized = normalized.replace("ّ", "").replace("ْ", "").replace("ٌ", "").replace("ٍ", "")
    return " ".join(normalized.split())

# ==============================================================
# Curriculum Replay Buffer
# ==============================================================
def collect_curriculum_replay_samples(dataset_name, current_set_size):
    """
    Collect partial/chunked curriculum samples as replay buffer.
    This prevents catastrophic forgetting of curriculum patterns while training on augmented data.

    Args:
        dataset_name: Name of dataset (e.g., "Quran-A")
        current_set_size: Size of current training set (to calculate 10% replay buffer)

    Returns:
        List of tuples: [(file, transcription, target_seconds, target_words), ...]
    """
    CHUNK_DURATION = 1.3  # seconds per chunk
    WORDS_PER_CHUNK = 1   # words per chunk

    curriculum_replay_samples = []

    # Find all text files
    text_dir = f"../datasets/{dataset_name}/text"
    all_text_files = sorted(glob.glob(os.path.join(text_dir, "*.txt")))

    # For "all" mode, include all parts
    relevant_surah_parts = []
    for text_file in all_text_files:
        basename = os.path.basename(text_file)
        surah_part = basename.replace('.txt', '')
        relevant_surah_parts.append((text_file, surah_part))

    if not relevant_surah_parts:
        return curriculum_replay_samples

    # Calculate replay buffer size as 10% of current set
    replay_buffer_size = max(int(current_set_size * 0.1), 10)

    # Distribute evenly across surah parts
    samples_per_surah = max(1, replay_buffer_size // len(relevant_surah_parts))

    for text_file, surah_part in relevant_surah_parts:
        # Load transcriptions
        with open(text_file, "r", encoding="utf-8") as f:
            transcriptions = [line.strip() for line in f if line.strip()]

        surah_num = surah_part.split('-')[0]

        # Load mel files
        if '-' in surah_part and len(surah_part.split('-')) > 1 and surah_part.split('-')[1]:
            mel_files = sorted(glob.glob(f"../datasets/{dataset_name}/mels/normal/{surah_num}/{surah_part}/{surah_part}-*.pt"))
        else:
            mel_files = sorted(glob.glob(f"../datasets/{dataset_name}/mels/normal/{surah_num}/{surah_part}-*.pt"))

        if not mel_files:
            mel_files = sorted(glob.glob(f"../datasets/{dataset_name}/mels/normal/{surah_num}/{surah_part}/{surah_part}-*.pt"))

        if len(mel_files) > 0 and len(mel_files) == len(transcriptions):
            # Sample randomly
            num_samples = min(samples_per_surah, len(mel_files))
            indices = random.sample(range(len(mel_files)), num_samples)

            for idx in indices:
                mel_file = mel_files[idx]
                text = transcriptions[idx]

                # Get audio duration and calculate curriculum stages
                mel_features = torch.load(mel_file, map_location='cpu', weights_only=True)
                audio_duration = mel_features.shape[0] / 100.0
                num_words = len(text.split())

                num_chunks = int(audio_duration / CHUNK_DURATION)
                max_chunks = min(num_chunks, num_words)

                # Create curriculum samples at different difficulty levels
                for chunk_count in range(1, max_chunks + 1):
                    target_seconds = chunk_count * CHUNK_DURATION
                    target_words = chunk_count * WORDS_PER_CHUNK

                    curriculum_replay_samples.append((
                        mel_file,
                        text,
                        target_seconds,
                        target_words
                    ))

    # Shuffle and limit to replay_buffer_size
    random.shuffle(curriculum_replay_samples)
    curriculum_replay_samples = curriculum_replay_samples[:replay_buffer_size]

    if len(curriculum_replay_samples) > 0:
        print(f"  Curriculum replay buffer size: {len(curriculum_replay_samples)} partial segments")

    return curriculum_replay_samples

# ==============================================================
# Calculate accuracy
# ==============================================================
def calculate_accuracy(model, segment_files, transcriptions, vocab, device, sample_size=100):
    """Calculate overall accuracy on regular (non-augmented) segments only"""
    model.eval()
    total_correct = 0
    total_tokens = 0

    # Randomly sample segments if dataset is large (shuffle each time for variety)
    if len(segment_files) > sample_size:
        indices = random.sample(range(len(segment_files)), sample_size)
        sampled_files = [segment_files[i] for i in indices]
        sampled_transcriptions = [transcriptions[i] for i in indices]
    else:
        sampled_files = segment_files
        sampled_transcriptions = transcriptions

    with torch.no_grad():
        for seg_file, expected_text in zip(sampled_files, sampled_transcriptions):
            # Load precomputed mel features
            mel_features = load_mel_features(seg_file)
            audio_batch = mel_features.transpose(0, 1).unsqueeze(0).to(device)

            # Calculate audio duration from mel spectrogram
            # For 8kHz audio with hop_length=80: duration = (time_frames * hop_length) / sample_rate
            time_frames = mel_features.shape[0]
            sample_rate = 8000
            hop_length = 80
            audio_duration = (time_frames * hop_length) / sample_rate

            # Generate
            generated = model.generate(
                audio_batch,
                max_new_tokens=50,
                temperature=1.0,
                min_tokens=1,
                use_sampling=False,
                audio_duration_seconds=audio_duration
            )
            tokens = generated[0].tolist()

            # Clean tokens
            if tokens and tokens[0] == 1:
                tokens = tokens[1:]
            if 2 in tokens:
                tokens = tokens[:tokens.index(2)]

            generated_words = [vocab[idx] for idx in tokens if idx < len(vocab)]
            generated_text = " ".join(generated_words)

            # Token-level accuracy (word-by-word comparison)
            expected_words = expected_text.split()
            min_len = min(len(expected_words), len(generated_words))
            total_correct += sum(1 for i in range(min_len) if generated_words[i] == expected_words[i])
            total_tokens += len(expected_words)

    accuracy = (total_correct / total_tokens * 100) if total_tokens > 0 else 0.0
    return accuracy

# ==============================================================
# Main training
# ==============================================================
def main():
    if len(sys.argv) < 3:
        print("Usage: python3 train_augmented.py <dataset_name> <surah_part|all>")
        print("Examples:")
        print("  python3 train_augmented.py Quran-A all            # Train all parts")
        print("  python3 train_augmented.py Quran-A 001            # Train specific part")
        print("  python3 train_augmented.py Quran-A 002-04         # Train specific part")
        sys.exit(1)

    dataset_name = sys.argv[1]
    surah_part = sys.argv[2]

    # Check if training all parts or single part
    if surah_part == "all":
        # Train all parts mode
        train_all_parts(dataset_name)
    else:
        # Train single part mode
        train_single_part(dataset_name, surah_part)

def train_all_parts(dataset_name):
    """Train on ALL segments across ALL surah parts with augmentation"""

    print(f"\n{'='*60}")
    print(f"TRAINING WITH AUGMENTED DATA - DATASET: {dataset_name}")
    print(f"{'='*60}\n")

    # Paths
    vocab_path = "../models/vocabulary.json"
    model_path = "../models/muhaffez_whisper.pt"
    datasets_dir = f"../datasets/{dataset_name}"

    # Load vocabulary
    with open(vocab_path, "r", encoding="utf-8") as f:
        vocab = json.load(f)
    print(f"Vocabulary size: {len(vocab)}")

    # Find ALL text files in dataset
    text_files = sorted(glob.glob(f"{datasets_dir}/text/*.txt"))
    if not text_files:
        print(f"❌ No text files found in {datasets_dir}/text/")
        sys.exit(1)

    # Collect regular (non-augmented) segments for accuracy testing
    regular_segment_files = []
    regular_transcriptions = []

    # Collect ALL segments (regular + augmented) for training
    all_training_segments = []
    all_training_transcriptions = []

    for text_file in text_files:
        surah_part = os.path.splitext(os.path.basename(text_file))[0]
        surah_num = surah_part.split('-')[0]
        mels_dir = f"{datasets_dir}/mels/normal/{surah_num}"
        mels_augmented_dir = f"{datasets_dir}/mels/augmented"

        # Load transcriptions
        with open(text_file, "r", encoding="utf-8") as f:
            transcriptions = [line.strip() for line in f if line.strip()]

        # Find regular mel feature files
        if '-' in surah_part and len(surah_part.split('-')) > 1 and surah_part.split('-')[1]:
            mel_files = sorted(glob.glob(f"{mels_dir}/{surah_part}/{surah_part}-*.pt"))
        else:
            mel_files = sorted(glob.glob(f"{mels_dir}/{surah_part}-*.pt"))

        if not mel_files:
            mel_files = sorted(glob.glob(f"{mels_dir}/{surah_part}/{surah_part}-*.pt"))

        if len(transcriptions) != len(mel_files):
            print(f"⚠️  Warning: Mismatch in {surah_part}: {len(transcriptions)} texts vs {len(mel_files)} mel files")
            continue

        # Add regular segments
        regular_segment_files.extend(mel_files)
        regular_transcriptions.extend(transcriptions)
        all_training_segments.extend(mel_files)
        all_training_transcriptions.extend(transcriptions)

        print(f"  Loaded {len(mel_files)} regular segments from {surah_part}")

        # Find PRECOMPUTED augmented mel feature files (pitch and speed variations)
        # These were generated by generate_mels.py and saved to mels/augmented/
        augmented_variations = [
            'pitch/minus4', 'pitch/minus2', 'pitch/plus2', 'pitch/plus4',
            'speed/minus20', 'speed/minus10', 'speed/plus10', 'speed/plus20'
        ]

        augmented_count = 0
        has_augmented_data = False
        for aug_type in augmented_variations:
            # Check both patterns: with and without subdirectory
            aug_mel_files = sorted(glob.glob(f"{mels_augmented_dir}/{aug_type}/{surah_num}/{surah_part}/{surah_part}-*.pt"))
            if not aug_mel_files:
                aug_mel_files = sorted(glob.glob(f"{mels_augmented_dir}/{aug_type}/{surah_num}/{surah_part}-*.pt"))

            if aug_mel_files:
                # Each augmented file corresponds to the same transcription
                all_training_segments.extend(aug_mel_files)
                all_training_transcriptions.extend(transcriptions)
                augmented_count += len(aug_mel_files)
                has_augmented_data = True

        if augmented_count > 0:
            print(f"  Loaded {augmented_count} augmented segments from {surah_part}")

        # Only include regular segments if they have augmented data
        # This ensures we're training only on 40-mel format
        if not has_augmented_data:
            # Remove the regular segments we just added
            regular_segment_files = regular_segment_files[:-len(mel_files)]
            regular_transcriptions = regular_transcriptions[:-len(transcriptions)]
            all_training_segments = all_training_segments[:-len(mel_files)]
            all_training_transcriptions = all_training_transcriptions[:-len(transcriptions)]
            print(f"  Skipping {surah_part} - no augmented data available")

    regular_segments_count = len(regular_segment_files)
    total_training_segments = len(all_training_segments)
    augmented_segments_count = total_training_segments - regular_segments_count

    print(f"\n✓ Regular segments: {regular_segments_count}")
    print(f"✓ Augmented segments: {augmented_segments_count}")
    print(f"✓ Training on 40-mel spectrograms (8kHz audio)")
    print(f"✓ Loading precomputed mels from: {datasets_dir}/mels/")
    print(f"✓ Augmented mels from: {datasets_dir}/mels/augmented/")

    # Convert all training segments to tuples: (file, text, target_seconds, target_words)
    # Regular and augmented segments use full-length (None, None)
    all_training_tuples = []
    for seg_file, text in zip(all_training_segments, all_training_transcriptions):
        all_training_tuples.append((seg_file, text, None, None))

    print(f"✓ Total training samples: {len(all_training_tuples)}\n")

    # Initialize or load model
    model = EncoderDecoderTransformer(
        vocab_size=len(vocab),
        d_model=128,
        n_encoder_layers=4,
        n_decoder_layers=4,
        n_heads=4,
        d_ff=512,
        dropout=0.1
    )

    if os.path.exists(model_path):
        print(f"\nLoading existing model from {model_path}...")
        model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
        print(f"✓ Model loaded successfully! Continuing training.")
    else:
        print(f"\n⚠️  No existing model found. Starting from scratch.")

    model = model.to(device)

    # Training setup with custom LR decay strategy
    learning_rate = 1e-3
    min_lr = 1e-7
    lr_decay_factor = 0.5  # Decay by 50%

    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=0.01)
    criterion = nn.CrossEntropyLoss(ignore_index=-100, label_smoothing=0.1)

    print(f"\nTraining Configuration:")
    print(f"  Initial Learning Rate: {learning_rate:.1e}")
    print(f"  LR Decay Factor: {lr_decay_factor} (50% reduction)")
    print(f"  Minimum Learning Rate: {min_lr:.1e}")
    print(f"  Strategy: Decay LR when loss increases, stop at {min_lr:.1e}")

    # Calculate initial accuracy
    initial_acc = calculate_accuracy(model, regular_segment_files, regular_transcriptions, vocab, device)
    print(f"\nInitial accuracy: {initial_acc:.1f}%")

    # Training loop
    best_loss = float('inf')
    prev_loss = float('inf')
    start_time = time.time()
    checkpoint_time = start_time  # Time of last checkpoint (for relative timing)
    epoch = 0

    while True:
        model.train()
        total_loss = 0.0
        total_iterations = 0

        # Shuffle all training samples
        random.shuffle(all_training_tuples)

        for seg_file, text, target_sec, target_wrd in all_training_tuples:
            # Load precomputed mel features (with optional truncation for curriculum samples)
            mel_features = load_mel_features(seg_file, target_seconds=target_sec)
            audio_batch = mel_features.transpose(0, 1).unsqueeze(0).to(device)

            # Extract target text (truncate for curriculum samples)
            if target_wrd:
                words = text.split()
                if len(words) < target_wrd:
                    continue
                target_text = " ".join(words[:target_wrd])
            else:
                target_text = text

            if not target_text:
                continue

            # Tokenize
            text_tokens = tokenize_text(target_text, vocab)
            full_sequence = [1] + text_tokens + [2]
            input_ids = torch.tensor([full_sequence[:-1]], dtype=torch.long, device=device)
            labels = torch.tensor([full_sequence[1:]], dtype=torch.long, device=device)

            # Forward
            logits = model(mel_features=audio_batch, text_ids=input_ids)
            loss = criterion(logits.view(-1, logits.size(-1)), labels.view(-1))

            # Backward
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += loss.item()
            total_iterations += 1

        if total_iterations == 0:
            print(f"⚠️  Warning: No valid training samples. Stopping.")
            break

        avg_loss = total_loss / total_iterations
        current_lr = optimizer.param_groups[0]['lr']

        # Save best model
        if avg_loss < best_loss:
            best_loss = avg_loss
            torch.save(model.state_dict(), model_path)

        # Check accuracy every 10 epochs
        accuracy_str = ""
        current_acc = 0
        if epoch == 0 or (epoch + 1) % 10 == 0:
            current_acc = calculate_accuracy(model, regular_segment_files, regular_transcriptions, vocab, device)
            accuracy_str = f" | Accuracy={current_acc:.0f}%"

        # Format time: seconds if < 60s, minutes if >= 60s, hours if >= 60m
        elapsed_from_checkpoint = time.time() - checkpoint_time
        if elapsed_from_checkpoint >= 3600:
            hours = int(elapsed_from_checkpoint // 3600)
            minutes = int((elapsed_from_checkpoint % 3600) // 60)
            time_str = f"{hours}h {minutes}m" if minutes > 0 else f"{hours}h"
        elif elapsed_from_checkpoint >= 60:
            time_str = f"{int(round(elapsed_from_checkpoint / 60))}m"
        else:
            time_str = f"{int(round(elapsed_from_checkpoint))}s"

        # Print epoch info
        print(f"Epoch {epoch+1}/500 | Loss={avg_loss:.4f}{accuracy_str} | Time={time_str}", flush=True)

        # Reset checkpoint time after printing
        checkpoint_time = time.time()

        # Custom LR decay: reduce by 10% when loss increases
        if avg_loss > prev_loss:
            old_lr = current_lr
            new_lr = max(old_lr * lr_decay_factor, min_lr)
            if new_lr != old_lr:
                for param_group in optimizer.param_groups:
                    param_group['lr'] = new_lr
                print(f"  Loss increased ({prev_loss:.4f} → {avg_loss:.4f}), reducing LR to: {new_lr:.1e}")
                current_lr = new_lr

        # Update prev_loss for next iteration
        prev_loss = avg_loss

        # Stop if learning rate reaches minimum
        if current_lr <= min_lr:
            print(f"\n✓ Stopping: Learning rate reached minimum ({min_lr:.1e})", flush=True)
            break

        # Stop if accuracy reaches 100%
        if current_acc >= 100.0:
            print(f"\n✓ Stopping: Accuracy reached 100%", flush=True)
            break

        epoch += 1

    # Save final model
    torch.save(model.state_dict(), model_path)
    print(f"\nFinal model saved to: {model_path}")

    # Calculate and output final accuracy
    final_acc = calculate_accuracy(model, regular_segment_files, regular_transcriptions, vocab, device)
    print(f"FINAL_ACCURACY: {final_acc:.0f}%")

def train_single_part(dataset_name, surah_part):
    """Train on a single surah part with augmentation"""

    print(f"\n{'='*60}")
    print(f"TRAINING WITH AUGMENTED DATA - PART: {surah_part}")
    print(f"Dataset: {dataset_name}")
    print(f"{'='*60}\n")

    # Paths
    vocab_path = "../models/vocabulary.json"
    model_path = "../models/muhaffez_whisper.pt"
    datasets_dir = f"../datasets/{dataset_name}"

    # Load vocabulary
    with open(vocab_path, "r", encoding="utf-8") as f:
        vocab = json.load(f)
    print(f"Vocabulary size: {len(vocab)}")

    surah_num = surah_part.split('-')[0]
    mels_dir = f"{datasets_dir}/mels/normal/{surah_num}"
    mels_augmented_dir = f"{datasets_dir}/mels/augmented"

    # Load transcriptions
    text_path = f"{datasets_dir}/text/{surah_part}.txt"
    if not os.path.exists(text_path):
        print(f"❌ Error: Text file not found: {text_path}")
        sys.exit(1)

    with open(text_path, "r", encoding="utf-8") as f:
        transcriptions = [line.strip() for line in f if line.strip()]

    # Find regular mel feature files
    if '-' in surah_part and len(surah_part.split('-')) > 1 and surah_part.split('-')[1]:
        mel_files = sorted(glob.glob(f"{mels_dir}/{surah_part}/{surah_part}-*.pt"))
    else:
        mel_files = sorted(glob.glob(f"{mels_dir}/{surah_part}-*.pt"))

    if not mel_files:
        mel_files = sorted(glob.glob(f"{mels_dir}/{surah_part}/{surah_part}-*.pt"))

    if not mel_files:
        print(f"❌ Error: No mel files found for {surah_part}")
        sys.exit(1)

    if len(transcriptions) != len(mel_files):
        print(f"⚠️  Warning: Mismatch: {len(transcriptions)} texts vs {len(mel_files)} mel files")

    # Collect regular (non-augmented) segments for accuracy testing
    regular_segment_files = list(mel_files)
    regular_transcriptions = list(transcriptions)

    # Collect ALL segments (regular + augmented) for training
    all_training_segments = list(mel_files)
    all_training_transcriptions = list(transcriptions)

    print(f"  Loaded {len(mel_files)} regular segments from {surah_part}")

    # Find PRECOMPUTED augmented mel feature files
    augmented_variations = [
        'pitch/minus4', 'pitch/minus2', 'pitch/plus2', 'pitch/plus4',
        'speed/minus20', 'speed/minus10', 'speed/plus10', 'speed/plus20'
    ]

    augmented_count = 0
    for aug_type in augmented_variations:
        if '-' in surah_part and len(surah_part.split('-')) > 1 and surah_part.split('-')[1]:
            aug_mel_files = sorted(glob.glob(f"{mels_augmented_dir}/{aug_type}/{surah_num}/{surah_part}/{surah_part}-*.pt"))
        else:
            aug_mel_files = sorted(glob.glob(f"{mels_augmented_dir}/{aug_type}/{surah_num}/{surah_part}-*.pt"))

        if aug_mel_files:
            all_training_segments.extend(aug_mel_files)
            all_training_transcriptions.extend(transcriptions)
            augmented_count += len(aug_mel_files)

    if augmented_count > 0:
        print(f"  Loaded {augmented_count} augmented segments from {surah_part}")
    else:
        print(f"  ⚠️  No augmented data found for {surah_part}")

    regular_segments_count = len(regular_segment_files)
    total_training_segments = len(all_training_segments)
    augmented_segments_count = total_training_segments - regular_segments_count

    print(f"\n✓ Regular segments: {regular_segments_count}")
    print(f"✓ Augmented segments: {augmented_segments_count}")

    # Convert all training segments to tuples: (file, text, target_seconds, target_words)
    # Regular and augmented segments use full-length (None, None)
    all_training_tuples = []
    for seg_file, text in zip(all_training_segments, all_training_transcriptions):
        all_training_tuples.append((seg_file, text, None, None))

    # No replay buffer for per-part training (only used in "all" mode)
    print(f"✓ Total training samples: {len(all_training_tuples)}\n")

    # Initialize or load model
    model = EncoderDecoderTransformer(
        vocab_size=len(vocab),
        d_model=128,
        n_encoder_layers=4,
        n_decoder_layers=4,
        n_heads=4,
        d_ff=512,
        dropout=0.1
    )

    if os.path.exists(model_path):
        print(f"\nLoading existing model from {model_path}...")
        model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
        print(f"✓ Model loaded successfully! Continuing training.")
    else:
        print(f"\n⚠️  No existing model found. Starting from scratch.")

    model = model.to(device)

    # Training setup
    initial_lr = 1e-3
    min_lr = 1e-7
    lr_decay = 0.5
    optimizer = torch.optim.AdamW(model.parameters(), lr=initial_lr, weight_decay=0.01)
    criterion = nn.CrossEntropyLoss(ignore_index=-100, label_smoothing=0.1)

    print(f"\nStarting training on {total_training_segments} segments...")
    print(f"Initial Learning Rate: {initial_lr:.1e}")
    print(f"LR Decay: {lr_decay} (when loss increases)")
    print(f"Minimum LR: {min_lr:.1e}")

    # Calculate initial accuracy
    initial_acc = calculate_accuracy(model, regular_segment_files, regular_transcriptions, vocab, device)
    print(f"Initial accuracy: {initial_acc:.1f}%")

    # Training loop
    best_loss = float('inf')
    prev_loss = float('inf')
    start_time = time.time()
    checkpoint_time = start_time  # Time of last checkpoint (for relative timing)
    epoch = 0
    max_epochs = 500

    while epoch < max_epochs:
        model.train()
        total_loss = 0.0
        total_iterations = 0

        # Shuffle all training samples
        random.shuffle(all_training_tuples)

        for seg_file, text, target_sec, target_wrd in all_training_tuples:
            # Load precomputed mel features (with optional truncation for curriculum samples)
            mel_features = load_mel_features(seg_file, target_seconds=target_sec)
            audio_batch = mel_features.transpose(0, 1).unsqueeze(0).to(device)

            # Extract target text (truncate for curriculum samples)
            if target_wrd:
                words = text.split()
                if len(words) < target_wrd:
                    continue
                target_text = " ".join(words[:target_wrd])
            else:
                target_text = text

            if not target_text:
                continue

            # Tokenize
            text_tokens = tokenize_text(target_text, vocab)
            full_sequence = [1] + text_tokens + [2]
            input_ids = torch.tensor([full_sequence[:-1]], dtype=torch.long, device=device)
            labels = torch.tensor([full_sequence[1:]], dtype=torch.long, device=device)

            # Forward
            logits = model(mel_features=audio_batch, text_ids=input_ids)
            loss = criterion(logits.view(-1, logits.size(-1)), labels.view(-1))

            # Backward
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += loss.item()
            total_iterations += 1

        if total_iterations == 0:
            print(f"⚠️  Warning: No valid training samples. Stopping.")
            break

        avg_loss = total_loss / total_iterations

        # Save best model
        if avg_loss < best_loss:
            best_loss = avg_loss
            torch.save(model.state_dict(), model_path)

        # Check accuracy every 10 epochs
        accuracy_str = ""
        current_acc = 0
        if epoch == 0 or (epoch + 1) % 10 == 0:
            current_acc = calculate_accuracy(model, regular_segment_files, regular_transcriptions, vocab, device)
            accuracy_str = f" | Accuracy={current_acc:.0f}%"

        # Format time: seconds if < 60s, minutes if >= 60s, hours if >= 60m
        elapsed_from_checkpoint = time.time() - checkpoint_time
        if elapsed_from_checkpoint >= 3600:
            hours = int(elapsed_from_checkpoint // 3600)
            minutes = int((elapsed_from_checkpoint % 3600) // 60)
            time_str = f"{hours}h {minutes}m" if minutes > 0 else f"{hours}h"
        elif elapsed_from_checkpoint >= 60:
            time_str = f"{int(round(elapsed_from_checkpoint / 60))}m"
        else:
            time_str = f"{int(round(elapsed_from_checkpoint))}s"

        # Print progress every epoch
        print(f"Epoch {epoch+1} | Loss={avg_loss:.4f}{accuracy_str} | Time={time_str}", flush=True)

        # Reset checkpoint time after printing
        checkpoint_time = time.time()

        # Decay learning rate if loss increases
        if avg_loss > prev_loss:
            old_lr = optimizer.param_groups[0]['lr']
            new_lr = max(old_lr * lr_decay, min_lr)
            if new_lr != old_lr:
                for param_group in optimizer.param_groups:
                    param_group['lr'] = new_lr
                print(f"  Loss increased ({prev_loss:.4f} → {avg_loss:.4f}), reducing LR to: {new_lr:.1e}")

        current_lr = optimizer.param_groups[0]['lr']
        prev_loss = avg_loss

        # Stop if learning rate reaches minimum
        if current_lr <= min_lr:
            print(f"\n✓ Stopping: Learning rate reached minimum ({min_lr:.1e})", flush=True)
            break

        # Stop if accuracy reaches 100%
        if current_acc >= 100.0:
            print(f"\n✓ Stopping: Accuracy reached 100%", flush=True)
            break

        epoch += 1

    # Save final model
    torch.save(model.state_dict(), model_path)
    print(f"\nFinal model saved to: {model_path}")

    # Calculate and output final accuracy
    final_acc = calculate_accuracy(model, regular_segment_files, regular_transcriptions, vocab, device)
    print(f"FINAL_ACCURACY: {final_acc:.0f}%")


if __name__ == "__main__":
    main()
